// Dashboard controls share the existing card/queue.
export const COMPACT_CSS = `
.compact-heading{display:none}
.shell.compact{display:block;height:auto;min-height:0;border-radius:var(--ha-card-border-radius,18px);border:1px solid var(--ha-card-border-color,var(--line));box-shadow:var(--ha-card-box-shadow,none);overflow:clip}
.shell.compact[data-compact-background=artwork]{border-color:#ffffff26;box-shadow:inset 0 1px 0 #ffffff0d,0 8px 28px #00000012;background:linear-gradient(140deg,#36313fb8,#24212ec4 60%,#191722d4);backdrop-filter:blur(24px) saturate(125%);-webkit-backdrop-filter:blur(24px) saturate(125%)}
.shell.compact[data-compact-background=artwork]::after{content:'';position:absolute;inset:0;pointer-events:none;z-index:0;background:linear-gradient(145deg,#ffffff0d,transparent 42%,#08081324);border-radius:inherit}
.shell.compact[data-compact-background=artwork][data-theme=light]{border-color:#ffffff70;background:linear-gradient(145deg,#f6f2f9bf,#e8e3efb8 58%,#dddde7c2);box-shadow:inset 0 1px 0 #fff9,0 8px 28px #2820350d}
.shell.compact>.main,.shell.compact>.topbar,.shell.compact>.sidebar{display:none}
.compact-background{display:none}.shell.compact>.ambient{display:none}.shell.compact[data-compact-background=artwork]>.compact-background{display:block;position:absolute;inset:0;border-radius:inherit;overflow:hidden;pointer-events:none;z-index:0}.compact-background img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:blur(42px) brightness(.66) saturate(1.25);opacity:0;transition:opacity .7s ease}.compact-background img.visible{opacity:.72}.shell.compact[data-theme=light] .compact-background img{filter:blur(42px) saturate(.85)}.shell.compact[data-theme=light] .compact-background img.visible{opacity:.24}
.shell.compact .compact-heading{position:relative;z-index:1;display:flex;align-items:center;gap:8px;padding:12px 16px 0}
.compact-heading .compact-labels{flex:1;min-width:0}.compact-heading strong{display:block;font-size:12px;font-weight:600}.compact-heading small{display:block;font-size:10px;line-height:1.5;color:var(--muted)}
.compact-heading button{width:34px;min-width:34px;height:34px;min-height:34px;padding:7px}.compact-heading feiniu-icon{--mdc-icon-size:18px}
.shell.compact .dock{position:relative;inset:auto;transform:none;width:100%;height:auto;margin:0;display:grid;grid-template-columns:minmax(0,1fr) auto;grid-template-rows:auto 46px auto;gap:12px 6px;padding:16px;border:0;border-radius:0;background:none;box-shadow:none;backdrop-filter:none}
.shell.compact .mini-info{grid-column:1/-1;grid-row:1;gap:14px;width:100%}.shell.compact .mini-cover{width:64px;height:64px;border-radius:12px}.shell.compact .mini-text strong{font-size:18px;font-weight:600;line-height:1.4}.shell.compact .mini-text small{font-size:12px;line-height:1.5;margin-top:4px}
.shell.compact #controls{grid-column:1;grid-row:2;justify-content:flex-start;gap:0}.shell.compact #controls #button-mode{display:inline-flex}.shell.compact #controls button{min-width:36px;width:36px;height:40px;padding:8px}.shell.compact #controls feiniu-icon{--mdc-icon-size:20px}.shell.compact #controls .main{width:48px;min-width:48px;height:46px;padding:9px}.shell.compact #controls .main feiniu-icon{--mdc-icon-size:28px}
.shell.compact .dock-tools{display:flex;grid-column:2;grid-row:2;gap:0}.shell.compact .dock-tools>button[data-mode],.shell.compact .dock-stop{display:none}.shell.compact .dock-tools button{width:36px;min-width:36px}
.shell.compact .progress{grid-column:1/-1;grid-row:3;display:grid;grid-template-columns:1fr 1fr;gap:6px}.shell.compact .progress input{grid-column:1/-1;grid-row:1;width:100%;background:color-mix(in srgb,var(--text) 24%,transparent)}.shell.compact .progress span{display:block;font-size:10px}.shell.compact #duration{text-align:right}
.shell.compact #status{position:static;grid-column:1/-1;transform:none;max-width:100%;white-space:normal;padding:0;background:none;font-size:11px}
.shell.compact-rich .dock{grid-template-rows:64px 136px 46px 24px}.shell.compact-rich #controls,.shell.compact-rich .dock-tools{grid-row:3}.shell.compact-rich .progress{grid-row:4}.shell.compact-rich #status{display:none}
#compact-stage{display:none}.shell.compact-rich #compact-stage{display:block;grid-column:1/-1;grid-row:2;position:relative;width:100%;height:136px;min-width:0}
#compact-artwork{width:100%;height:100%;padding:4px;position:relative;background:none}#compact-artwork img{height:120px;width:120px;object-fit:cover;border-radius:14px;box-shadow:0 6px 20px #0003}#compact-artwork>feiniu-icon{--mdc-icon-size:72px;color:var(--dim)}
#compact-caption{position:absolute;bottom:0;left:0;right:0;z-index:2;text-align:center;font-size:10px;line-height:1.4;color:var(--muted);pointer-events:none;padding:5px;background:color-mix(in srgb,var(--surface) 85%,transparent);border-radius:8px}#compact-caption:empty{display:none}#compact-caption.loading::before{content:' ';display:inline-block;width:8px;height:8px;border:1px solid currentColor;border-right-color:transparent;border-radius:50%;margin-right:6px;animation:compact-loading .9s linear infinite}@keyframes compact-loading{to{transform:rotate(360deg)}}
.shell.compact .lyric-panel{position:relative;display:block;height:100%;width:100%;min-height:0}.shell.compact #lyric-lines{height:100%;width:100%;text-align:center;mask-image:linear-gradient(transparent,#000 18%,#000 82%,transparent)}
.shell.compact .lyric-row{display:block;position:relative;margin:0 0 12px;padding:0 40px}.shell.compact #lyric-lines p{font-size:16px;line-height:1.6;font-weight:600;letter-spacing:-.2px}.shell.compact #lyric-lines .lyric-seek{position:absolute;right:0;top:50%;transform:translateY(-50%);width:42px;min-height:26px;gap:1px;padding:2px;font-size:8px}.shell.compact .lyric-seek feiniu-icon{--mdc-icon-size:9px}
.shell.compact #lyric-lines pre{font-size:13px;line-height:1.8;padding:16px 10px}.shell.compact #lyric-lines .empty{font-size:12px;padding:12px;text-align:center}
.shell.compact #lyric-tools{flex-direction:row;gap:2px;top:0;right:0}.shell.compact #lyric-tools button{width:24px;min-width:24px;height:24px;min-height:24px;padding:4px}.shell.compact #lyric-tools feiniu-icon{--mdc-icon-size:13px}.shell.compact #lyric-tools #lyric-offset-value{font-size:8px}.shell.compact #lyric-notice{top:28px;right:0;font-size:10px;padding:5px}
.shell.compact #error{position:relative;top:auto;left:auto;right:auto;margin:0 16px 12px}
.shell.compact-rich .lyric-panel,.shell.compact-rich #compact-artwork{animation:compact-reveal .2s ease-out}@keyframes compact-reveal{from{opacity:0}to{opacity:1}}
@media(prefers-reduced-motion:reduce){.shell.compact-rich .lyric-panel,.shell.compact-rich #compact-artwork,.shell.compact #compact-caption::before{animation:none}.compact-background img{transition:none}}
.shell.compact #volume-pop{right:0;bottom:calc(100% + 8px);max-width:calc(100cqw - 32px)}
.expanded-dialog{position:fixed;inset:0;margin:auto;padding:0;width:min(1440px,calc(100vw - 24px));height:calc(100dvh - 24px);max-width:none;max-height:none;border:1px solid #ffffff26;border-radius:20px;background:#24212c;color:#fff;box-shadow:0 24px 80px #0006;overflow:hidden;container-type:inline-size}
.expanded-dialog::backdrop{background:#0008;backdrop-filter:blur(6px)}
.expanded-heading{height:44px;display:flex;align-items:center;padding:4px 12px 4px 20px;gap:12px;font-size:12px}.expanded-heading #expanded-title{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.expanded-heading button{width:36px;min-width:36px;height:36px;min-height:36px;padding:8px}
.expanded-frame{width:100%;height:100%;container-type:inline-size;background:inherit;color:inherit}.expanded-frame>.shell{height:calc(100% - 44px);min-height:0}.expanded-dialog[data-theme=light]{background:#f1eff3;color:#202027}
.expanded-frame:fullscreen{width:100vw;height:100dvh}
@media(max-width:600px){.expanded-dialog{width:100%;height:100dvh;border:0;border-radius:0}}
`;
